---
- hosts: all
  sudo: yes
  remote_user: vagrant
  vars:
    web_server: httpd
    state: latest
  tasks:
    - name: Install a web server
      yum: name={{ web_server }} state={{ state }}
      #sudo: yes
    - name: Enable chkconfig httpd
      service: name={{ web_server }} state=started enabled=yes

